import {
  RoleNotFoundError,
  RoleAlreadyExistsError,
  PermissionNotFoundError,
  PermissionAlreadyExistsError,
  DomainError,
  ValidationError,
  DatabaseError,
  UserNotFoundError,
  UserAlreadyExistsError,
  InvalidEmailError,
  AuthenticationError,
  AuthorizationError,
  InactiveUserError,
} from "../../../core/domain/errors.js";

export const errorHttpMap = new Map<Function, number>([
  [RoleAlreadyExistsError, 409],
  [RoleNotFoundError, 404],
  [PermissionNotFoundError, 404],
  [PermissionAlreadyExistsError, 409],
  [DomainError, 400],
  [ValidationError, 400],
  [DatabaseError, 500],
  [UserNotFoundError, 404],
  [UserAlreadyExistsError, 409],
  [InvalidEmailError, 400],
  [AuthenticationError, 401],
  [AuthorizationError, 403],
  [InactiveUserError, 401],
]);
